### ISSUE TITLE
Target For 32 Bit

### ISSUE THREAD

**Issue by dc6581574** [Kudaes/DInvoke_rs#9]
Hi I am trying to build for 32 bit but I keep getting similar issues . I am simply using dynamic invoke and not any syscalls or other unsupported stuff. 
I have tried using these two so far 
$ rustup target add i686-pc-windows-msvc
$ rustup target add i686-pc-windows-gnu 
![image](https://github.com/Kudaes/DInvoke_rs/assets/165047186/c51860bb-4eec-4371-bd13-5ef496c58d5b)

**Comment by dc6581574** [comment]
Update on this one . In the file dmanager-0.1.0\src\lib.rs:157:39 
I modified the casting in the lines 157 and 107 from ` **let addr: PVOID = std::mem::transmute(address);**` to  `**let addr: *mut c_void = address as *mut c_void;** `

And for the time being the commented out the function ` pub unsafe extern "system" fn breakpoint_handler (exceptioninfo: *mut ExceptionPointers) -> i32` in the dinvoke-0.1.0\src\lib.rs .

**Comment by Kudaes** [comment]
Yes, ATM I'm adding some conditional compilation to address that kind of issues. The Dinvoke functionality itself should be x86 compatible, but some of the other features (like indirect syscalls or hardware breakpoints) are not, thats why your compilation is failing.

I'll work to fix it on the next version, which I hope to be released in up to 2-3 weeks.

**Comment by Kudaes** [comment]
Hi again @dc6581574 ,

I've pushed a new commit with a quick fix for your issue. Could you try again and let me know if it is working now?

**Comment by dc6581574** [comment]
Hey , I tried again and there are still issues with it in the `invoke-0.1.3\src\lib.rs:` in the HWBP function 
![image](https://github.com/Kudaes/DInvoke_rs/assets/165047186/2e70ba8f-8020-4bdb-8b7f-9dfaf26aedba)

**Comment by dc6581574** [comment]
I updated it from the crates . Makes sense . Thanks
